import "../env.js";

export const CORE = [
  "/js/env.js",
  "/js/db.js",
  "/js/core/renderGuard.js",
  "/js/services/selection.js",
  "/js/utils.js",
  "/js/render.js",
  "/js/db_compat.js",
  "/js/ui/Toast.js",
  "/js/ui/Confirm.js",
  "/js/data/settings.js",
  "/js/ical.js",
  "/js/migrations.js",
  "/js/presets.js",
  "/js/filters.js",
  "/js/ui_shims.js",
  "/js/templates.js",
  "/js/state/selectionStore.js",
  "/js/state/actionBarGuards.js",
  "/js/header_ui.js",
  "/js/ui/notifications_panel.js",
  "/js/add_contact.js",
  "/js/quick_add.js",
  "/js/doccenter_rules.js",
  "/js/contacts.js",
  "/js/partners.js",
  "/js/partners_modal.js",
  "/js/contacts_merge.js",
  "/js/dash_range.js",
  "/js/importer.js",
  "/js/reports.js",
  "/js/commissions.js",
  "/js/notifications.js",
  "/js/calendar_impl.js",
  "/js/calendar.js",
  "/js/calendar_ics.js",
  "/js/calendar_actions.js",
  "/js/post_funding.js",
  "/js/qa.js",
  "/js/bulk_log.js",
  "/js/print.js",
  "/js/app.js",
  "/js/settings_forms.js",
  "/js/services/pipelineStages.js",
  "/js/services/softDelete.js",
];

export const PATCHES = [
  "/js/patch_20250923_baseline.js",
  "/js/patch_20250924_bootstrap_ready.js",
  "/js/patch_20250926_ctc_actionbar.js",
  "/js/patch_2025-09-26_phase1_pipeline_partners.js",
  "/js/patch_2025-09-26_phase2_automations.js",
  "/js/patch_2025-09-26_phase3_dashboard_reports.js",
  "/js/patch_2025-09-26_phase4_polish_regression.js",
  "/js/patch_2025-09-27_doccenter2.js",
  "/js/patch_2025-09-27_contact_linking_5A.js",
  "/js/patch_2025-09-27_contact_linking_5B.js",
  "/js/patch_2025-09-27_contact_linking_5C.js",
  "/js/patch_2025-09-27_nth_bundle_and_qa.js",
  "/js/patch_2025-09-27_masterfix.js",
  "/js/patch_2025-09-27_release_prep.js",
  "/js/patch_2025-10-02_baseline_ux_cleanup.js",
  "/js/patch_2025-10-02_medium_nice.js",
  "/js/patch_2025-09-27_merge_ui.js",
  "/js/patch_2025-09-27_phase6_polish_telemetry.js",
  "/js/patch_2025-10-03_quick_add_partner.js",
  "/js/patch_2025-10-03_automation_seed.js",
  "/js/patch_2025-10-07_wire_diag_and_stage_tracker.js",
  "/js/patch_2025-10-07_actionbar_wiring_safety.js",
  "/js/patch_2025-10-07_settings_profile_photo_ui.js",
];

export default {
  CORE,
  PATCHES,
};

