import "../env.js";

export const CORE = [
  "/js/env.js",
  "/js/db.js",
  "/js/core/renderGuard.js",
  "/js/services/selection.js",
  "/js/utils.js",
  "/js/render.js",
  "/js/db_compat.js",
  "/js/ui/Toast.js",
  "/js/ui/Confirm.js",
  "/js/data/settings.js",
  "/js/ical.js",
  "/js/migrations.js",
  "/js/presets.js",
  "/js/filters.js",
  "/js/ui_shims.js",
  "/js/templates.js",
  "/js/state/selectionStore.js",
  "/js/state/actionBarGuards.js",
  "/js/header_ui.js",
  "/js/ui/notifications_panel.js",
  "/js/add_contact.js",
  "/js/quick_add.js",
  "/js/doccenter_rules.js",
  "/js/contacts.js",
  "/js/partners.js",
  "/js/partners_modal.js",
  "/js/contacts_merge.js",
  "/js/dash_range.js",
  "/js/importer.js",
  "/js/reports.js",
  "/js/commissions.js",
  "/js/notifications.js",
  "/js/calendar_impl.js",
  "/js/calendar.js",
  "/js/calendar_ics.js",
  "/js/post_funding.js",
  "/js/qa.js",
  "/js/bulk_log.js",
  "/js/print.js",
  "/js/app.js",
  "/js/settings_forms.js",
  "/js/services/pipelineStages.js",
  "/js/services/softDelete.js",
];

export const PATCHES = [
  "/js/patch_2025-10-02_baseline_ux_cleanup.js",
  "/js/patch_2025-10-02_medium_nice.js",
  "/js/patch_2025-10-03_quick_add_partner.js",
  "/js/patch_2025-10-03_calendar_ics_button.js",
  "/js/patch_2025-10-03_automation_seed.js",
  "/js/patch_2025-10-07_actionbar_center.js",
  "/js/patch_2025-10-07_wire_diag_and_stage_tracker.js",
  "/js/patch_2025-10-07_dashboard_initial_refresh.js",
  "/js/patch_2025-10-07_settings_profile_photo_ui.js",
  "/js/patch_2025-10-08_selection_guard.js",
  "/js/patch_2025-10-08_actionbar_harden.js",
  "/js/patch_2025-10-08_partners_edit_router.js",
  "/js/calendar_actions.js",
];

export default {
  CORE,
  PATCHES,
};

